pipeline {
agent any

```
stages {

    stage('Checkout') {
        steps {
            git branch: 'main',
                credentialsId: 'git_id',
                url: 'https://github.com/Sridhar0119/DEVOPS-COllEGE-EVENT.git'
        }
    }

    stage('Build Frontend Image') {
        steps {
            sh 'docker build -t frontend-app -f Dockerfile.frontend .'
        }
    }

    stage('Build Backend Image') {
        steps {
            sh 'docker build -t backend-app -f Dockerfile.backend .'
        }
    }

    stage('Deploy Containers') {
        steps {
            sh '''
            docker stop frontend-app backend-app || true
            docker rm frontend-app backend-app || true

            docker run -d \
            --name backend-app \
            -p 5000:5000 \
            backend-app

            docker run -d \
            --name frontend-app \
            -p 80:80 \
            frontend-app
            '''
        }
    }
}

post {
    success {
        echo 'Deployment Successful'
    }
    failure {
        echo 'Deployment Failed'
    }
}
```

}
