pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                git 'https://github.com/Sridhar0119/DEVOPS-COllEGE-EVENT.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t college-event-app .'
            }
        }

        stage('Deploy Container') {
            steps {
                sh '''
                docker stop college-event-app || true
                docker rm college-event-app || true

                docker run -d \
                --name college-event-app \
                -p 80:3000 \
                college-event-app
                '''
            }
        }
    }
}