sonar.projectKey=ubdt-utkarsh
sonar.projectName=UBDT Utkarsh
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/.next/**,**/k8s/**,**/public/**
sonar.sourceEncoding=UTF-8
sonar.language=ts
sonar.typescript.tsconfigPath=tsconfig.json
